# Firebase Configuration
REACT_APP_FIREBASE_API_KEY=your_firebase_api_key_here
REACT_APP_FIREBASE_AUTH_DOMAIN=your_firebase_auth_domain_here
REACT_APP_FIREBASE_PROJECT_ID=your_firebase_project_id_here
REACT_APP_FIREBASE_STORAGE_BUCKET=your_firebase_storage_bucket_here
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=your_firebase_messaging_sender_id_here
REACT_APP_FIREBASE_APP_ID=your_firebase_app_id_here
REACT_APP_FIREBASE_MEASUREMENT_ID=your_firebase_measurement_id_here
# Firebase Admin SDK Configuration
STORAGE_BUCKET_NAME=your_storage_bucket_name_here
STORAGE_BUCKET_URL=your_storage_bucket_url_here
# Stripe Configuration (TEST MODE)
REACT_APP_STRIPE_PUBLISHABLE_KEY=your_stripe_publishable_key_here
STRIPE_SECRET_KEY=your_stripe_secret_key_here
STRIPE_WEBHOOK_SECRET=your_stripe_webhook_secret_here
# REACT_APP_APISPORTS_KEY=your_apisports_key_here
REACT_APP_USE_EMULATORS="false"
NODE_ENV=production
REACT_APP_APISPORTS_KEY=your_apisports_key_here
TELEGRAM_BOT_TOKEN=your_telegram_bot_token_here
REACT_APP_TELEGRAM_BOT_USERNAME=your_telegram_bot_username_here
TELEGRAM_CHAT_ID=your_telegram_chat_id_here
DOMAIN=your_domain_here
# Facebook & Instagram API Keys
FB_PAGE_ACCESS_TOKEN=your_fb_page_access_token_here
FB_USER_ACCESS_TOKEN=your_fb_user_access_token_here
FB_PAGE_ID=your_fb_page_id_here
IG_USER_ID=your_ig_user_id_here
# Twitter API Keys
X_APP_ID=your_twitter_app_id_here
X_APP_NAME=your_twitter_app_name_here
X_ACCESS_TOKEN=your_twitter_access_token_here
X_ACCESS_TOKEN_SECRET=your_twitter_access_token_secret_here
X_BARRER_TOKEN=your_twitter_bearer_token_here
X_CALLBACK=your_twitter_callback_url_here
X_WEBSITE=your_twitter_website_url_here
X_CLIENT_ID=your_twitter_client_id_here
X_CLIENT_SECRET=your_twitter_client_secret_here
X_CONSUMER_KEY=your_twitter_consumer_key_here
X_CONSUMER_SECRET=your_twitter_consumer_secret_here
# Restriction Configs
RESTRICTED_STATES=AZ,TN,MD,LA
ALLOWED_COUNTRIES=PK,US
RESTRICTION_HARDFAIL=false
# NEW KEYS ADDED ON 25-05-2024 END HERE
REACT_APP_RESTRICTED_STATES=AZ,TN,MD,LA
REACT_APP_ALLOWED_COUNTRIES=PK,US
REACT_APP_RESTRICTION_HARDFAIL=false